Add empty adjusted Xcode project for JourneySquad App.
ios-course/link-team-project pull request #21
Opened 2023-05-05 09:15 UTC by kirpichonok

# What 

Added initial Xcode project to start development of JourneySquad application. There are set up minimum deployment target, supported devices, modes and platform, project version.

# Why

It's part of work on [issue #1](https://github.com/ios-course/link-team-project/issues/1). 

# How 

Added folder with Xcode project to the root directory.

### There are set up next values:

- Base SDK - iOS 

- iOS Deployment Target - 16.0

- Current Project Version - 0.0.0

- Supported Destinations  - iPhone

- Minimum Deployments - iOS 16.0

- iPhone Orientation - Portrait only

- Identity: 
  -  Version - 0.0.0
  - Build - 0.0.0

### Added SwiftLint script to build phase

    export PATH="$PATH:/opt/homebrew/bin"
    if which swiftlint > /dev/null; then
      swiftlint --config ../.swiftlint.yml
    else
      echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"

2023-05-05 10:20 UTC, YuliaNastiushkina reviewed
I cannot build project, I have next issue:
`One of the path in DEVELOPMENT_ASSET_PATH does not exist.`

Does anyone else have this issue, or is it a mistake on my side?

2023-05-05 10:31 UTC, kirpichonok commented
Yes, I have the same error. I'm figuring out.

2023-05-05 10:46 UTC, kirpichonok commented
I've updated the project. Please, try again.

2023-05-05 11:33 UTC, YuliaNastiushkina approved these changes
LGTM

2023-05-05 12:43 UTC, dersim-davaod requested changes
LGTM, except the version settings.

2023-05-05 12:43 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 0.0.0;
You have set up the marketing version in the target, but did not do this in the project. Why?

2023-05-05 13:32 UTC, levvaa approved these changes
LGTM

2023-05-08 10:05 UTC, kirpichonok commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 0.0.0;
It's my mistake. I wanted to set up versions only for PROJECT and not to set up versions for TARGETS. 
Fixed

2023-05-08 10:12 UTC, kirpichonok commented
I set up the target's marketing version to **$MARKETING_VERSION** and the project version to **CURRENT_PROJECT_VERSION**. They will be updated with PROJECT's project and marketing versions.

2023-05-08 13:22 UTC, dersim-davaod approved these changes
LGTM

2023-05-08 13:28 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Assets.xcassets/AccentColor.colorset/Contents.json
> +{
May be we can delete the content, but we need this directory to build the project. I don't see the need to delete this file and then to think how to push this dir to repo.

2023-05-08 13:29 UTC, merged