Bill model
ios-course/link-team-project pull request #30
Opened 2023-05-13 07:26 UTC by kirpichonok

# What 

Added enum `BillValidationError` with errors that can be caused by incorrect input data for the bill's fields.

# Why 

It's part of the work on issue #16. 

# How 

- Added enum `BillValidationError` with necessary error cases that listed in the [_Set of Errors_](https://github.com/ios-course/link-team-project/issues/16#:~:text=in%20the%20future.-,Set%20of%20Errors,-invalidParticipantName%20%2D%20indicates%20invalid) section.

- Added tests for `errorDescription` property of the `BillValidationError`.

2023-05-13 10:54 UTC, dersim-davaod requested changes
Did a quick review.
Consider improvements to change the implementation so it's easy to use it from the client's code.

Also seems you haven't run linters. Why?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +/// Indicates error that can be caused by incorrect input data for the bill.
nit:
```suggestion
import Foundation

/// Indicates error that can be caused by incorrect input data for the bill.
```

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
nit:
```suggestion
    case tooLongParticipantName
```

Otherwise it might be confusing: was that too long name of the bill?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
Should we use associated value here as well?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Occurs when the participant's name doesn't contain no one letter.
Is that possible to have name with no letters?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case noOneLetterInName(String)
What does the associated value contain?
Should we document it?

Please review the rest of code.

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Occurs when negative value is passed for fields that  can't be such.
nit:
```suggestion
    /// Occurs when negative value is passed for fields that can't be such.
```

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case zeroSumOfBill
Should we have an error for case when the sum of bill is negative? Should it be the same case?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case balanceIsViolated
nit:
what is a "balance"? do we have such field in the `Bill`?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    var errorDescription: String? {
Make the separate extension and put the `errorDescription` there.

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    var errorDescription: String? {
Does the `errorDescription` have default documentation?
Should we override it?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "Error! This is a date in the future: \(futureDate)."
You don't need to put prefixes here. Client's code decides on their own:
```suggestion
            return "This is a date in the future: \(futureDate)."
```

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The money can't be negative: \(negativeSum)."
The documentation says:
> Occurs when negative value is passed for fields that can't be such

but here you mention money.

Should the documentation be more specific?
Should the case name be more specific (e.g. `negativeAmountOfMoney`)?

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.tooLongName.errorDescription
You can put all these cases (to check presence in API) into one test.

2023-05-13 10:54 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        let futureDate = Date.now + 10
nit: magic numbers. Make the code clear and show your intentions:

```suggestion
        let tenSecondsDuration: TimeInterval = 10
        let tenSecondsFromNowDate = Date.now + tenSecondsDuration
```

2023-05-13 12:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
I think that we don't need because the name can be too long and can contain thousands of signs. But I think we can show in the error only first 50 signs.

2023-05-13 12:48 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Occurs when the participant's name doesn't contain no one letter.
I meant any alphabet unit. If you input the name ">>" , this name doesn't contain letter.

2023-05-13 12:51 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +/// Indicates error that can be caused by incorrect input data for the bill.
Fixed

2023-05-13 12:51 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
Fixed

2023-05-13 13:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
ok, my question is why do we need this type of error?

let's discuss the following situation:

we're trying to create the bill with 10 participants and getting the `toLongName` error. what should we do? do we want to highlight the field with the long name? how we should know in code which field (participant) exceeds the max length?

(we can do this using various number of techniques, my point is please make sure you understand what you're doing)

2023-05-15 05:30 UTC, levvaa requested changes

2023-05-15 05:30 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates, that  the overall sum of the bill is equal to zero.
nit: 

```suggestion
    /// Indicates, that the overall sum of the bill is equal to zero.
```

2023-05-15 06:10 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongName
Thanks, I understand. 
Fixed

2023-05-15 07:15 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Occurs when the participant's name doesn't contain no one letter.
I have changed this item in [AC](https://github.com/ios-course/link-team-project/issues/16) to 'emptyName` and changed implementation accordingly. Look, please.

2023-05-15 08:15 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case zeroSumOfBill
I thought to indicate a negative value of the sum by `negativeNumber` error. But it looks like a good idea to combine negative and zero values of the sum of the bill to one case. Thanks. 

Fixed.

2023-05-15 08:16 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    var errorDescription: String? {
Fixed

2023-05-15 08:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case balanceIsViolated
"Balance" is equality of the overall sum of the bill and the sum of the participants's sums. 
"Equality"  can be instead of "balance". 

Fixed

2023-05-15 08:25 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    var errorDescription: String? {
Fixed

2023-05-15 08:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "Error! This is a date in the future: \(futureDate)."
Fixed

2023-05-15 08:54 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The money can't be negative: \(negativeSum)."
Fixed

2023-05-15 09:01 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.tooLongName.errorDescription
Thanks, fixed.

2023-05-15 09:02 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        let futureDate = Date.now + 10
Fixed

2023-05-15 09:13 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates, that  the overall sum of the bill is equal to zero.
Fixed

2023-05-15 11:56 UTC, levvaa requested changes

2023-05-15 12:13 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ContentView.swift
Should I open a separate PR?

2023-05-15 12:17 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case equalityIsViolated
@levvaa 
What do you mean? 
Why doesn't the case `equalityIsViolated` have a parameter?

2023-05-15 12:20 UTC, levvaa commented on JourneysSquad/JourneysSquad/ContentView.swift
resolve in slack

2023-05-15 12:35 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case equalityIsViolated
I mean, that in the documentation there are not information about parameter. Why it's haven't be here? Or we shouldn't show this information

2023-05-16 07:30 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case equalityIsViolated
What parameter do you suggest if to take into account description of the `equalityIsViolated`? 🙂

2023-05-16 13:08 UTC, dersim-davaod requested changes
Overall looks good.
Please consider improvements:

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case equalityIsViolated
nit:

```suggestion
    case incorrectEstimatedSumOfTheBill
```
or
```suggestion
    case sumOfBillSplitsDoesNotMatchSumOfTheBill
```

Otherwise I might think there's a violation of women rights.

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The name length exceeds 50 characters: \(tooLongName)."
nit:
```suggestion
            return "The length of the person's name exceeds the maximum allowed length: \(tooLongName)."
```

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The money can't be negative: \(negativeAmount)."
nit:

```suggestion
            return "The amount of money <= 0: \(negativeAmount)."
```

to be consistent with the rest of descriptions: I thought you write not the rule, but the reason of the error.

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.tooLongParticipantName(name: "Abu Ibn .....").errorDescription
nit:

Why do you need this strange names here?
```suggestion
        _ = BillValidationError.tooLongParticipantName(name: "").errorDescription
```

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.tooLongParticipantName(name: "Abu Ibn .....").errorDescription
Please review the rest of code.

2023-05-16 13:08 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +                       "The name length exceeds 50 characters: \(longName).")
Review the rest of code.

2023-05-17 07:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquad.xcodeproj/xcshareddata/xcschemes/JourneysSquad.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed

2023-05-17 08:22 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +                       "The name length exceeds 50 characters: \(longName).")
Fixed

2023-05-17 08:25 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case tooLongParticipantName(name: String)
Fixed

2023-05-17 08:32 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case invalidFormatOfMoneyAmount(number: Decimal)
Fixed

2023-05-17 08:33 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case incorrectSumOfBill(sum: Decimal)
Fixed

2023-05-17 08:35 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case futureDate(Date)
Fixed

2023-05-17 08:38 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    case equalityIsViolated
Fixed

2023-05-17 08:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The money can't be negative: \(negativeAmount)."
Fixed

2023-05-17 08:52 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "Invalid format of money amount: \(invalidFormattedNumber). Maximum accuracy is two decimal places."
Fixed

2023-05-17 08:54 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The sum of the bill must equal the sum of all the participants's sums."
Fixed

2023-05-17 08:57 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.tooLongParticipantName(name: "Abu Ibn .....").errorDescription
Fixed

2023-05-17 12:01 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ContentView.swift
> +        VStack {}
I'll fix it in the separate PR.

2023-05-17 12:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ContentView.swift
> +        VStack {}
The issue [#37](https://github.com/ios-course/link-team-project/issues/37)

2023-05-17 12:42 UTC, dersim-davaod requested changes
Several nits:

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates too long participant's name.
I thought we agreed to use the `person` word.

```suggestion
    /// Indicates too long person's name.
```

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates too long participant's name.
Please review the rest of code.

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The name: \(emptyPersonName) contains only spaces or no one sign."
The description doesn't quite match the name of the error.

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.emptyPersonName(name: " ").errorDescription
nit:
```suggestion
        _ = BillValidationError.emptyPersonName(name: "").errorDescription
```

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        XCTAssertEqual(actualErrorDescription, expectedErrorDescription)
You can avoid blank lines:

```suggestion
        let name = "test"
        let expectedErrorDescription = "The length of the person's name exceeds the maximum allowed length: \(name)."
        let actualErrorDescription = BillValidationError.tooLongPersonName(name: name).errorDescription

        XCTAssertEqual(actualErrorDescription, expectedErrorDescription)
```

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        let amount: Decimal = -4
What do you test here?
Will the test pass if you change the line: 

```suggestion
        let amount: Decimal = 1
```

?

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +            "This is a date in the future: \(tenSecondsFromNowDate)."
nit:

Why you haven't created separate constants for actual/expected values like you have done in the previous tests?

Be consistent please.

2023-05-17 12:42 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The name: \(emptyPersonName) contains only spaces or no one sign."
nit:

Be consistent please:
`sign` is not a `character`.

2023-05-17 13:48 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates too long participant's name.
@dersim-davaod 
Is it regarding the name of a person? If I write about spendings, is it correct?

> Indicates that the sum of the bill doesn't equal the sum of all the participants's pays.

I think it doesn't make documentation hard readable, but expresses more clearly the essence of the sentence content.

2023-05-17 14:25 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        let amount: Decimal = -4
It was discussed on call

2023-05-17 14:43 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Indicates too long participant's name.
Fixed

2023-05-17 14:45 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        _ = BillValidationError.emptyPersonName(name: " ").errorDescription
Fixed

2023-05-17 14:47 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +        XCTAssertEqual(actualErrorDescription, expectedErrorDescription)
Fixed

2023-05-17 14:49 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +            "This is a date in the future: \(tenSecondsFromNowDate)."
Fixed

2023-05-17 14:50 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +            return "The name: \(emptyPersonName) contains only spaces or no one sign."
Fixed

2023-05-17 17:17 UTC, levvaa requested changes

2023-05-17 17:46 UTC, dersim-davaod approved these changes
LGTM

2023-05-17 19:28 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +
Fixed

2023-05-17 19:33 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +    /// Occurs when a negative number is passed for fields that reflects the amount of money and can't be such.
Fixed

2023-05-17 19:36 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +}
Yes, you can. We process only cases that are described. You can suggest to add new cases and create issue for further sprints.

2023-05-17 19:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +    func testErrorDescriptionReturnsCorrespondingMessageForTooLongPersonNameError() {
We check not only that message is returned, but we also compare `actualErrorDescription` with `expectedErrorDescription`. 
I think that "CorrespondingMessage" is more accurate.

2023-05-17 19:45 UTC, kirpichonok commented
@levvaa Please, resolve conversations if you are satisfy with answers.

2023-05-18 04:18 UTC, levvaa requested changes

2023-05-18 04:18 UTC, levvaa commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +
nit:

Trailing Whitespace Violation

2023-05-18 05:01 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +
Are you sure? I run my project and don't have any warning.

2023-05-18 05:25 UTC, levvaa commented on JourneysSquad/JourneysSquadTests/Model/BillValidationErrorTests.swift
> +
resolved in slack

2023-05-18 05:25 UTC, levvaa approved these changes
LGTM

2023-05-18 08:34 UTC, dersim-davaod approved these changes
LGTM

2023-05-18 08:35 UTC, merged