Add `Bill` model implementation.
ios-course/link-team-project pull request #32
Opened 2023-05-15 14:47 UTC by kirpichonok

# What 

Added an implementation of the `Bill` model. 
 
# Why

It closes #16.

# How 

- Add type `Bill` with fields to save bill's data. 

- Added validation of the input data  to the `Bill` initialiser.

- The type `BillValidationError` adopted `Equatable` protocol to verify the received errors during testing.

- Added `BillTests` file with tests.

2023-05-15 16:00 UTC, YuliaNastiushkina reviewed
I have a few questions, please check.

2023-05-16 07:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +        participantSpents: [String: Decimal],
You're right. Fixed

2023-05-16 07:24 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +        participantSpent = participantSpents
Fixed

2023-05-16 07:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +        guard date < Date() else { throw BillValidationError.futureDate(date) }
Fixed

2023-05-16 13:32 UTC, dersim-davaod requested changes
Please consider the following improvements:

2023-05-16 13:32 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +    static let allowedDescriptionLength = 50
Please review the rest of code.

2023-05-16 13:32 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +    private static func hasMoreThanTwoDecimalPlaces(_ number: Decimal) -> Bool {
The implementation is fragile. Can you improve it?

2023-05-17 14:59 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +/// Bill with related data.
Fixed

2023-05-17 15:05 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +    /// The user's notes to the bill.
Fixed

2023-05-17 15:11 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +    static let allowedDescriptionLength = 50
Fixed

2023-05-17 15:14 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +    static let allowedDescriptionLength = 50
Fixed

2023-05-18 09:20 UTC, dersim-davaod requested changes
Please consider minor improvements for now:

2023-05-18 09:20 UTC, dersim-davaod commented on CHANGELOG.md
> +- Add `Bill` model into the model layer - [#32](https://github.com/ios-course/link-team-project/pull/32)
Why you haven't added the `Add` prefix earlier?
Be consistent please: either use the prefix or not.

2023-05-18 09:20 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +extension BillValidationError: Equatable {
Seems you can put the extension into the test target.

2023-05-18 09:20 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let date = Date.now + 10
Magic numbers and non-clear semantics. Please improve using the approach we have discussed earlier.

2023-05-18 09:37 UTC, kirpichonok commented on CHANGELOG.md
> +- Add `Bill` model into the model layer - [#32](https://github.com/ios-course/link-team-project/pull/32)
Fixed

2023-05-18 09:43 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillValidationError.swift
> +extension BillValidationError: Equatable {
Fixed

2023-05-18 09:45 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let date = Date.now + 10
Fixed

2023-05-18 12:30 UTC, levvaa requested changes

2023-05-18 12:30 UTC, levvaa commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsIncorrectEstimatedSumOfTheBilErrorlWhenSumOfBillIsNotEqualToSumOfPersonPaid() {
nit:

```suggestion
    func testInitThrowsIncorrectEstimatedSumOfTheBillErrorlWhenSumOfBillIsNotEqualToSumOfPersonPaid() {
```

2023-05-18 13:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/Billl.swift
> +    /// - Throws: The `BillValidationError` if the bill can't be created or doesn't make sense.
I've update this part of documentation. Please, check out.

2023-05-18 13:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsEmptyPesonNameErrorWhenOneOfNamesIsEmptyString() {
Fixed

2023-05-18 13:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsTooLongPersonNameErrorWhenOneOfNamesIsLongerThenMaxPersonNameLength() {
Fixed

2023-05-18 13:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsEmptyPesonNameErrorWhenOneOfNamesIsEmptyString() {
Fixed

2023-05-18 13:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsTooLongPersonNameErrorWhenOneOfNamesIsLongerThenMaxPersonNameLength() {
Fixed

2023-05-18 13:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsIncorrectEstimatedSumOfTheBilErrorlWhenSumOfBillIsNotEqualToSumOfPersonPaid() {
Fixed

2023-05-18 13:44 UTC, levvaa requested changes

2023-05-18 13:44 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/Billl.swift
Check the name of file

2023-05-18 14:14 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/Billl.swift
It's epic fail 😬
Fixed

2023-05-19 05:20 UTC, levvaa approved these changes
LGTM

2023-05-19 12:32 UTC, dersim-davaod requested changes
Consider improvements to increase maintainability.

2023-05-19 12:32 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +                description: "Description",
Please review the rest of code.

2023-05-19 12:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Extensions/BillValidationErrorExtension.swift
> +extension BillValidationError: Equatable {
Fixed

2023-05-19 14:13 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let name = " "
Fixed

2023-05-19 14:14 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let nameTwo = " "
Fixed

2023-05-19 14:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +                description: "Description",
Fixed

2023-05-19 14:30 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +                date: Date.now
Fixed

2023-05-19 16:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        }
I've done another way. Look, please.

2023-05-19 16:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let name = String(repeating: "A",
Fixed

2023-05-19 16:45 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Extensions/BillValidationErrorExtension.swift
> +    static func == (_ lhs: BillValidationError, _ rhs: BillValidationError) -> Bool {
Fixed

2023-05-19 16:47 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let bill = try? Bill(personPaid: ["A": 1],
Fixed

2023-05-19 18:06 UTC, dersim-davaod requested changes
Please address all the comments above before re-requesting review.

2023-05-20 12:47 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +                XCTFail("Unexpected error")
Fixed

2023-05-20 13:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        let amount: Decimal = -1
Fixed

2023-05-20 13:34 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +    func testInitThrowsEmptyPesonNameErrorWhenOneOfNamesContainsOnlySpacesAndAnotherNameIsEmpty() {
I have rewritten the test. I think the name now corresponds to content.

2023-05-20 13:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/Bill.swift
> +        guard date <= Date() else { throw BillValidationError.theDateIsInFuture(date) }
I think that `guard` operator is more suitable for early exit or error throwing.

2023-05-20 13:47 UTC, kirpichonok commented
Sorry, I've missed hidden conversations.

2023-05-22 07:56 UTC, levvaa approved these changes
LGTM
Just pay attention to nit

2023-05-22 07:56 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/Bill.swift
> +    /// Create a new instance of bill.
nit:

```suggestion
    /// Creates a new instance of bill.
```

2023-05-22 07:58 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/Bill.swift
> +    /// Create a new instance of bill.
Fixed

2023-05-22 13:36 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        }
Still see the same issue.
Let me know when the new version arrives.

2023-05-22 13:39 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +        description _: String,
Please, review the rest of code.
Line 49, for example.

2023-05-22 14:23 UTC, YuliaNastiushkina reviewed
Great job, but this PR so huge.
It difficult to review, so I cannot guarantee you that the review was of the best quality.
Please try not to make the PR so big next time.

I have some questions, please check.

2023-05-22 15:58 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Model/BillTests.swift
> +        }
```swift
        do {
            _ = try Bill(
                personPaid: [nameThatExceedsMaxLengthOne: 1, nameThatExceedsMaxLengthTwo: 1],
                description: "",
                sumOfBill: 1,
                date: .now
            )
        } catch BillValidationError.tooLongPersonName {
            XCTAssert(true)
        } catch {
            XCTFail("Unexpected error: \(error)")
        }
```
I founded one more variant. 

@dersim-davaod

2023-05-23 06:14 UTC, dersim-davaod approved these changes
LGTM

2023-05-23 09:10 UTC, YuliaNastiushkina reviewed
Please address all the comments above before re-requesting review.

2023-05-23 09:37 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillModel.swift
> +        description _: String,
Fixed

2023-05-23 09:40 UTC, YuliaNastiushkina approved these changes
LGTM

2023-05-23 10:24 UTC, levvaa approved these changes
LGTM

2023-05-23 10:25 UTC, merged