Add file with History of Operations. Includes title and button "Add"
ios-course/link-team-project pull request #34
Opened 2023-05-16 09:21 UTC by levvaa

### What

Added basic file with UI for History ofOperations screen. 

### Why

It's part of the work on issue [Create UI for History of Operations screen](https://github.com/ios-course/link-team-project/issues/3)

### How

- Added file for History of Operations
- Added main title of the screen
- Added button "Add".

2023-05-16 10:52 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +/// A view that displays a list of bills grouped by date.
/// Displays a list of bills grouped by date.

2023-05-16 10:54 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +/// A view that displays a list of bills grouped by date.
```suggestion
/// Displays a list of bills grouped by date.
```

2023-05-16 10:58 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +    var bills: BillsModel = .init()
```suggestion
    var bills =  BillsModel ()
```
I suggest to use simpler syntax.

2023-05-16 13:07 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +    /// A computed property that groups the bills by date.
```suggestion
    /// Shows the bills grouped by date.
```

2023-05-16 13:10 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/HistoryOfOperationsView.swift
> +            Button(action: {}) { // TODO: Add action.
Why do you need `// TODO: ...` here? 
Is it your incomplete task?

2023-05-16 13:11 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/HistoryOfOperationsView.swift
> +            Button(action: {}) { // TODO: Add action.
Why didn't  you use navigation bar settings to add `Title` and `Button`?

2023-05-16 13:11 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/HistoryOfOperationsView.swift
> +        .padding(.horizontal, 15)
I think that `.padding(.horizontal, 5)` is enough.

2023-05-16 13:13 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillsModel.swift
> +struct BillsModel {
The name  `DummyBillModel` makes its purpose cleaner.

2023-05-16 13:16 UTC, kirpichonok requested changes
- I suggest to create a folder View and add to that `view` files. You can add a folder "History of Operations" inside folder "View". 
- Bring your code in line with our formatting rules.
- Update CHANGELOG.md
- Update Target's and Project's versions.

2023-05-16 14:12 UTC, dersim-davaod requested changes
I see a lot of warnings. Please fix them.
Also please format the code before pushing the changes to the remote.
Additionally, please consider the following improvements:

2023-05-16 14:12 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +    var groupedBills: [String: [[String: Any]]] {
So each time you access the `groupedBills` the operation of grouping is performed. What is the complexity of such operation?

2023-05-16 14:12 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +            (bill["date"] as? String) ?? ""
Magic string.

2023-05-16 14:12 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +            // Iterate over each group of bills, sorted by date in descending order.
Please remove comments.
If you do believe the comment should be here, that probably means your code is not readable.

2023-05-16 14:12 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +            ForEach(groupedBills.sorted(by: { $0.key > $1.key }), id: \.key) { date, bills in
Shouldn't we prepare all the data so the view just displays it (that means no additional operations/sorting/etc)?

Could you please think of another view model?

2023-05-16 14:12 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/HistoryOfOperations/BillListView.swift
> +            ForEach(groupedBills.sorted(by: { $0.key > $1.key }), id: \.key) { date, bills in
The implementation is hard to read.

First, please extract the section and the row into a separate view.

2023-05-18 12:36 UTC, levvaa commented
the current pull request will be split into subtasks with separate pull requests

2023-05-19 05:36 UTC, levvaa commented
Issue has been split into smaller issues #44 #45 #42 #43 with separate pull requests.

2023-05-19 05:36 UTC, closed without merging