BillRowView implementation
ios-course/link-team-project pull request #46
Opened 2023-05-19 05:40 UTC by levvaa

### What

Added implementation of screen "History of operations"

Why

It's part of the work on issue #42 

How

- Added file for Bill Row
- Created UI for Bill Row

2023-05-19 06:35 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                        .font(.system(size: 14))
Do you try to resolve this question using 
[truncationMode](https://developer.apple.com/documentation/swiftui/text/truncationmode(_:)) as we discussed?

2023-05-19 06:39 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                        Text("\(participants[0]), \(participants[1]), ...")
If the names of the participants are "Ura", "Ira" and "Ivan", we can't display them in one row? 
Why not?
And if the names are "Grigarovich Vladislav Anatolievich" and one more such name, we display them.

2023-05-19 06:50 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                let participants = ["Participant 1", "Participant 2", "Participant 3"]
```suggestion
                let participants = [
                "Participant 1", 
                "Participant 2",
                 "Participant 3",
                 ]
```
nit: 
It's easer to read.

2023-05-19 07:11 UTC, kirpichonok requested changes
### Check description:

- Can you add more description for PR?

- You are adding implementation of `BillRowView`, not screen "History of operations":

> - Added implementation of screen "History of operations"

- Do you plan to have one more PR for this issue? If you want to close this issue with this PR, use keywords `close` #, `closes #` and etc:`

> It's part of the work on issue [#42](https://github.com/ios-course/link-team-project/issues/42)

- `BillRowView` will be more suitable than `Bill Row`:

> -   Added file for Bill Row
> -   Created UI for Bill Row

### Format code:
You have to run SwiftFormat in the BillRowView file.

### Summary:
Consider comments and try to use DummyBill to hardcode input data.

2023-05-19 20:13 UTC, dersim-davaod requested changes
Glad to see the PR, thanks for your hard work! 💪🏼 
Did a quick review, please consider several improvements:

2023-05-19 20:13 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +                Text(bill.participants.joined(separator: ", "))
The view should get the prepared data.
It shouldn't perform such operations like `joined` (that's why we have view models).

2023-05-19 20:13 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let sum = "50.00 $"
nit:

The upcoming model won't contain the currency sign. Please be prepared for that and/or discuss it with @kirpichonok

2023-05-20 12:21 UTC, kirpichonok requested changes
I think you should think about view model as recommended.

2023-05-20 12:21 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +
The SwiftFormat deletes such empty lines.

2023-05-20 12:21 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    /// Participants who is on the account.
```suggestion
    /// Participants that paid within the bill.
```
You have such notation for property below.

2023-05-20 12:21 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let sum = "50.00 $"
```suggestion
    let sumOfBill = "50.00 $"
```
 It will express more certainly the meaning of the constant.

2023-05-22 04:23 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                        .font(.system(size: 14))
Hiding a large description was achieved using `.padding(Edge.Set.trailing, xx)`

2023-05-22 04:24 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                        Text("\(participants[0]), \(participants[1]), ...")
You're right. In the current implementation, hiding is based on the number of characters

2023-05-22 04:25 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                let participants = ["Participant 1", "Participant 2", "Participant 3"]
You right. 
In the current implementation with temporary data, I displayed two participants. I think describing them in one line doesn't make the code harder to read.

2023-05-22 04:27 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +    var bill: DummyBillModel
fixed. All missed documentation have been added.

2023-05-22 04:30 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +    var bill: DummyBillModel
In this case it was a mistake.
Has been changed to use `@ObservedObject var viewModel: BillRowViewModel` since I don't use the model anymore.
In new case i use variable because property wrapper can only be applied to a 'var'.

2023-05-22 04:32 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +            .padding(Edge.Set.trailing, 140)
I decide how many points I need using the simulator and keeping an eye on the current data display. In this case, for the expected result, I needed such a number of points.

2023-05-22 04:33 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +
fixed

2023-05-22 04:38 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +    var bill: DummyBillModel
You are absolutely right. model has been removed and DummyBillRowViewModel has been added.
This makes sense since the UI needs to receive processed data. Processing takes place in another layer.

DummyBillModel have been removed. The ВummyВillЬodel layer has been removed. Added DummyBillRowViewModel layer.

2023-05-22 04:38 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +struct BillRow: View {
name have been fixed

2023-05-22 04:39 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +struct DummyBillModel {
DummyBillModel have been removed.

2023-05-22 04:40 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let description = "Description"
Yes. It makes sense. 
This process has been moved to the view model, as this layer is responsible for preparing the data.

2023-05-22 04:40 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +                Text(bill.participants.joined(separator: ", "))
Yes. It makes sense.
This process has been moved to the view model, as this layer is responsible for preparing the data.

2023-05-22 04:42 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let description = "Description"
`DummyBillModel` have been removed. 
At the moment the instance is created in the preview in `BillRowView`.

2023-05-22 04:43 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let sum = "50.00 $"
discussed with @kirpichonok this point. Currency display is not needed now.

2023-05-22 04:44 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +
fixed

2023-05-22 04:45 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    let sum = "50.00 $"
fixed

2023-05-22 04:52 UTC, levvaa commented on JourneysSquad/JourneysSquad/Model/DummyBillModel.swift
> +    /// Participants who is on the account.
Documentation has been changed by semantic meaning.

2023-05-22 06:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRow.swift
I see you did not rename the file. Correct, please.

2023-05-22 06:32 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
fixed

2023-05-22 06:34 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +            .padding(Edge.Set.trailing, 120)
Why have you chosen such a number? Could the padding take less space? Then we will be able to display more text. 
Should we save the padding value as a constant?

2023-05-22 06:41 UTC, kirpichonok requested changes
I have some comments. Answer, please.

2023-05-22 06:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
We can set it to 2. It could provide additional space to output large numbers. Why not?

2023-05-22 06:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .frame(maxWidth: 50)
```suggestion
                .frame(maxWidth: 50)
                .minimumScaleFactor(0.6)
```
I think it could be better to use `minimumScaleFactor` to increase the count of visible digits in big numbers.

2023-05-22 06:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// A formatted string representing the members, separated by a comma.
```suggestion
    /// A formatted string representing the participants, separated by a comma.
```

2023-05-22 09:15 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
I think that it's not good idea, because I think that displaying numbers in two lines will not be very convenient and understandable for users. How do you think?

2023-05-22 09:17 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .frame(maxWidth: 50)
It seems to me that on small screens the text may turn out to be unreadable with this modifier.

2023-05-22 09:30 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// A formatted string representing the members, separated by a comma.
fixed

2023-05-22 10:19 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
I think that it could be better than to hide digits.

2023-05-22 10:24 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .frame(maxWidth: 50)
@levvaa 
We can set the font `body` for this field and decrease that with `minimumScaleFactor`.

2023-05-22 13:22 UTC, YuliaNastiushkina requested changes
Good job!
I have some questions, check please.

2023-05-22 13:22 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// The view model responsible for providing data to the view.
Make it simpler.
```suggestion
    /// The view model to provide data to the view.
```

2023-05-22 13:22 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                    .font(.system(size: 14))
Please, avoid "magic numbers" as we discussed with team.

2023-05-22 13:22 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +            .padding(Edge.Set.trailing, 120)
Remove that line and add `Spacer` as we discussed with team.

2023-05-22 13:22 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +/// The view model for a bill responsible for preparing and providing data for the view.
We know that it'a a model view :)
For what view it provide data ?
I'm not fully understand what you mean in this doc comment.

2023-05-22 13:22 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// Description of the bill.
Be more precise, this is not a description of the bill. This is a fixed raw value to represent in the view. What do you think ?

Review the rest of code.

2023-05-23 05:46 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// Description of the bill.
I didn't fully understand what you mean. This variable contains prepared description for display in the view model.

Do you mean that I should describe it as "a prepared description for the bill"?

2023-05-23 05:58 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                    .font(.system(size: 14))
Font sizes is used based on AC in issue. Do I need to create a separate enum inside the project for fonts now?

2023-05-23 06:06 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// The view model responsible for providing data to the view.
fixed

2023-05-23 06:06 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +            .padding(Edge.Set.trailing, 120)
fixed

2023-05-23 06:09 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +/// The view model for a bill responsible for preparing and providing data for the view.
Check please actual variant.

2023-05-23 06:11 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
Now the size of the amount increases in one line without hiding. Does this option suit you?

2023-05-23 09:03 UTC, YuliaNastiushkina requested changes

2023-05-23 09:03 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +/// The view model for a bill responsible for preparing and providing data for the view.
"Responsible for managing the data associated with a Bill row."
 
So it looks clearer or not? What do you think ?

2023-05-23 09:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
It'll be ok if the size of the font for the sum of the bill will be [body](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines) and the `minimumScaleFactor` will be used. I talked about it [here](https://github.com/ios-course/link-team-project/pull/46/files/603308eabdd390dedb2e4814135f1304280eb3e9#r1200315905).

2023-05-23 09:32 UTC, kirpichonok requested changes
Looks good but you need to addres question about font size from @YuliaNastiushkina and  this [comment](https://github.com/ios-course/link-team-project/pull/46/files/603308eabdd390dedb2e4814135f1304280eb3e9#r1200315905).

2023-05-23 09:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                    .font(.system(size: 14))
I suggest using the [body](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines) font for description.

2023-05-23 10:44 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .lineLimit(1)
Yes. I agree with you. Used body size for Description and Sum

2023-05-23 10:46 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// Description of the bill.
fixed

2023-05-23 11:14 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRow.swift
> +            .padding(Edge.Set.trailing, 120)
padding have been deleted.

2023-05-23 11:16 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                .frame(maxWidth: 50)
I didn't use minimumScaleFactor, because it can shows very little in small screens. Meanwhile, i used body fonts how you recommended.

2023-05-23 11:16 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +                    .font(.system(size: 14))
font size fixes to body.

2023-05-23 11:17 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +/// The view model for a bill responsible for preparing and providing data for the view.
Used your variant. It seems good.

2023-05-23 11:18 UTC, dersim-davaod requested changes
Please resolve conflicts.

2023-05-23 11:59 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
```suggestion
    }
    
    /// Font "Note" used as required [App style guidlines]
```
It should be a line here.

2023-05-23 12:05 UTC, kirpichonok approved these changes
LGTM excepting few remarks.

2023-05-23 12:33 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
fixed

2023-05-23 14:01 UTC, dersim-davaod reviewed
LGTM, however I have a few nits and a couple of questions:

2023-05-24 06:14 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +class BillRowViewModel: ObservableObject {
Obesrvable object needed to serve the state. Just now we don't need it, because we don't have data to serve. 
Fixed.

2023-05-24 07:24 UTC, YuliaNastiushkina approved these changes
LGTM, however I have a couple questions.

2023-05-24 07:24 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
Do you really need this information ?
You may choose not to write documentation for a private interface.

2023-05-24 07:24 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
Agree with @kirpichonok.
@levvaa why do you think that it's not helpful ? In which case would it be useful for you?

2023-05-24 08:11 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
I think it's important to understand where specific font sizes come from.
How i can to understand, why body size is 20? Or note size is 14.

2023-05-24 08:59 UTC, dersim-davaod requested changes
Please consider improvements:

2023-05-24 08:59 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +    var description = "Description"
Could you please explain why the description is a variable here?

2023-05-24 08:59 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +import Foundation
Could you please explain why do you need the `Foundation` import here?

2023-05-24 08:59 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +import SwiftUI
Could you please explain why do you need the `SwiftUI` import here?

2023-05-24 09:13 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    /// Font "Note" used as required [App style guidlines]
Created thread for discuss in slack

2023-05-24 14:22 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +import Foundation
Here with this data we don't need it

2023-05-24 14:22 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +import SwiftUI
Here with this data we don't need it

2023-05-25 07:56 UTC, dersim-davaod reviewed
Few minor improvements:

2023-05-25 07:56 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
> +    var viewModel: BillRowViewModel
Could you please explain why the `viewModel` is a variable?

2023-05-25 07:56 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +final class BillRowViewModel {
nit:

Shouldn't that be Dummy model then (taking into account their current usage)?

2023-05-25 08:34 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
> +final class BillRowViewModel {
Yes. Now it's dummy model. Made the name appropriate to use

2023-05-25 08:38 UTC, dersim-davaod approved these changes
Great! LGTM 🚀

2023-05-25 08:56 UTC, merged