Create UI for screen `Add Bill`.
ios-course/link-team-project pull request #51
Opened 2023-05-24 08:08 UTC by kirpichonok

# What 

Added UI for screen `Add Bill` according to AC of issue #4. 

# Why 

This PR closes #4. 

# How

Added:
- `RoundedRectangleView` create label for the button `Save`.

- `DatePickFieldView` to display and input date.

- `CircleWithPlusView` create label for the button `+`.

- `DataInputFieldView` the text field to input.

- `AddBillView` shows completed screen.

2023-05-24 08:55 UTC, YuliaNastiushkina requested changes
Great job, thanks!
But please, try to make PR less in future.

I have a few questions and improvements, please check.

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .font(.system(size: fontBodySize, weight: .bold, design: .rounded))
```suggestion
                .font(.system(size: fontBodySize, weight: .bold, design: .default))
```

Our [App style guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines) doesn't contain font `.rounded`
Please, review the rest of code.

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .padding(.top)
Why do you use `.padding(.top)` here ?

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +        }
```suggestion
        }
        .padding()
```

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +                .padding(.top)
The same question:
Why do you use .padding(.top) here ?

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +    private let buttonCornerRadius: CGFloat = 10
Please, check corner radius for buttons in [App style guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines).

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +        RoundedRectangleView(label: "Hello")
Why do you use `label: "Hello"` ?

```suggestion
        RoundedRectangleView(label: "Save")
```

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +                Spacer()
Do you need `Spacer()` here ?

2023-05-24 08:55 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +/// A view for adding a bill with various details such as the sum of the bill,
```suggestion
/// A view for adding a bill with details.
```

2023-05-24 15:05 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .font(.system(size: fontBodySize, weight: .bold, design: .rounded))
Our guide contains the type of font. It's actually `default`. Our guide doesn't contain info about `design` and `weight`. 
May be we need to correct our fonts? I have some suggestions, but in this case I don't see violation of out style guide. 
What do you think about it?

2023-05-24 15:27 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +        }
I think we don't need to add `padding` because we use `padding` in the place of the usage.

2023-05-24 15:28 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +                .padding(.top)
To add additional space between title and date. Do you suggest to remove that to make this space less?

2023-05-24 15:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +    private let buttonCornerRadius: CGFloat = 10
fixed

2023-05-24 15:36 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +                               labelOfField: "What is it",
Fixed

2023-05-24 15:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +                Spacer()
Fixed

2023-05-24 15:50 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +/// A view for adding a bill with various details such as the sum of the bill,
>/// A view for adding a bill with details.
It triggers a questions: "What details? What are the details?"
Is it not?

2023-05-24 16:15 UTC, YuliaNastiushkina requested changes

2023-05-24 16:15 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +/// A view for adding a bill with various details such as the sum of the bill,
I think not, I can see details of bill in code below.
You don't need to repeat it in doc comments.

2023-05-24 16:15 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .font(.system(size: fontBodySize, weight: .bold, design: .rounded))
Yep, my bad. 
You can discuss your suggestions with team and after that add it to the [App style guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines).

2023-05-24 16:15 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .padding(.top)
Yes, it seems to me that now the space between them is large and we should remove that line.

2023-05-24 16:15 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +                .padding(.top)
Yes, it seems to me that now the space between them is large and we should remove that line.

2023-05-24 16:15 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +        }
But why you use `.padding()` in `DataInputFieldView` file and don't use in this file ?
Please, choose one style and use it in both files.

2023-05-25 09:34 UTC, dersim-davaod requested changes
Did a quick review for now.
Going to continue the review later.

2023-05-25 13:31 UTC, levvaa requested changes

2023-05-25 13:31 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/AddBillView/CircleWithPlusView.swift
> +            .padding(7)
magic number
Why you use this value? Why not 8

2023-05-25 13:31 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +    @State private var sumOfBill = ""
Can you explain why we need a `@State` now?

2023-05-25 13:31 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/AddBillView/CircleWithPlusView.swift
> +            .background(Color.black)
Should we have a different color for this button?

2023-05-25 13:31 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +/// A field to enter text with a label above one.
I don't full understand this documentation. Could you explain what does it mean or describe it differently

2023-05-26 07:27 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .padding(.top)
Fixed

2023-05-26 07:51 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +        }
Fixed

2023-05-26 08:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +                .padding(.top)
Fixed

2023-05-26 08:43 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +/// A view for adding a bill with various details such as the sum of the bill,
Fixed

2023-05-26 08:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +    @State var label: String
Fixed

2023-05-26 09:12 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +/// A black rectangle button with rounded corners and white text inside.
Thanks, fixed

2023-05-26 09:24 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +/// A view that allows selecting a calendar date.
Fixed

2023-05-26 09:25 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +    @Binding var value: Date
Fixed

2023-05-26 09:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +            Text("Date".uppercased())
Fixed

2023-05-26 09:28 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +            Text("Date".uppercased())
Fixed

2023-05-26 09:36 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +            DatePicker("", selection: $value, displayedComponents: .date)
Fixed

2023-05-26 09:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +    // MARK: - Private interface
Because internal is something that we have by default and thus that is meant by default.

2023-05-26 09:50 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +struct DatePickFieldView: View {
Fixed

2023-05-26 09:54 UTC, kirpichonok commented on CHANGELOG.md
> +- Screen `Add Bill` - [#51](https://github.com/ios-course/link-team-project/pull/51)
Fixed

2023-05-26 10:10 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/CircleWithPlusView.swift
> +        Image(systemName: "plus")
Fixed

2023-05-26 10:11 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/CircleWithPlusView.swift
> +            .padding(7)
Fixed

2023-05-26 10:12 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/AddBillView.swift
> +    @State private var sumOfBill = ""
Because `TextField` doesn't work without it.

2023-05-26 10:47 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/CircleWithPlusView.swift
> +            .background(Color.black)
Fixed

2023-05-27 09:19 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +/// A field to enter text with a label above one.
I've updated that.

2023-05-28 12:47 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .font(.system(size: fontBodySize, weight: .bold, design: .rounded))
Fixed

2023-05-29 04:56 UTC, kirpichonok commented
I've split this PR into 2. I've updated description of this PR and opened a new [PR](https://github.com/ios-course/link-team-project/pull/60).

2023-05-29 07:41 UTC, YuliaNastiushkina requested changes
Great job!
But I have some questions, check it please.

2023-05-29 07:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .multilineTextAlignment(alignment.textAlignment)
In the previous line, we set limits of 1 line for the text. So it seems that multilineTextAlignment(alignment.textAlignment) is redundant here.
What do you think ?

2023-05-29 07:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +            TextField(placeholder, text: $input)
Does placeholder disappear when I set cursor to the text field ?
Or it will be add later ?

2023-05-29 07:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldViewAlignment.swift
> +    /// The corresponding value of the `HorizontalAlignment`.
Correspond for what? :)

2023-05-29 07:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
I cannot enter text in preview mode. Please, check why.

2023-05-29 08:35 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .multilineTextAlignment(alignment.textAlignment)
It should be `multilineTextAlignment` for `TextField` element.

2023-05-29 08:35 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +            TextField(placeholder, text: $input)
It will disappear.

2023-05-29 08:38 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldViewAlignment.swift
> +    /// The corresponding value of the `HorizontalAlignment`.
Corresponding to the case.

2023-05-29 08:40 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
We've discussed that it's a correct behavior.

2023-05-30 06:39 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
I'm not sure about this.
I tried to enter text in preview mode and in the simulator, but I can't.
Should we be able to type text into `TextField` in this PR? Maybe I'm trying to do something that I can't :)

2023-05-30 06:39 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldViewAlignment.swift
> +    /// The corresponding value of the `HorizontalAlignment`.
It seems as non-understandable for me. What about suggestion below ?

```suggestion
    /// Value of `HorizontalAlignment` based on the alignment case.
```

2023-05-30 06:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +            TextField(placeholder, text: $input)
It will be implement in other PR or now ?
I don't understand your answer, sorry.

2023-05-30 06:41 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .multilineTextAlignment(alignment.textAlignment)
I'm sorry, but I still don't understand.

You use `.lineLimit()` on `TextField` and set a limit that text can be represented on 1 line.
After that, you use `.multilineTextAlignment` on `TextField` to say that there should be some alignment when the text is presented on multiple lines. But why, if you can only have 1 line?

2023-05-30 06:43 UTC, YuliaNastiushkina reviewed
I still have questions about the previous comments.
Check it please.

2023-05-30 12:51 UTC, dersim-davaod requested changes
Please consider the following improvements:

2023-05-30 12:51 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +        DataInputFieldView(input: .constant(""),
As we have discussed, please add more examples of the `DataInputFieldView` in the preview.

Please add at least one with a very long text for label/placeholder so it is easy to see what it looks like.

2023-05-30 12:51 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S294JL6K3Q;
Again: I see the updated development team.
Could you please explain why?

2023-05-30 12:51 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickerView.swift
> +struct DatePickerView: View {
```suggestion
struct DatePickerWithLabelView: View {
```

?

2023-05-30 12:51 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickerView.swift
> +/// A view with the label `Date` that allows selecting a calendar date by tapping on the field below the label.
```suggestion
/// A view that shows a date picker with the label containing a description text.
/// The date picker allows to select a speicifc day. 
```

2023-05-30 12:51 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickerView.swift
> +/// A view with the label `Date` that allows selecting a calendar date by tapping on the field below the label.
Please allow to parametrize the label's text. It would be useful for localization purposes at least.

2023-05-30 13:00 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +    // MARK: - Private interface
And what if we got `public` property later then?
Are we going to add `// MARKs` for internal interface there? :)

2023-05-30 13:02 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +    @State var label: String
I still see the same issue with unclear semantics in the latest PR's state (in a different file, though).

2023-05-31 07:55 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/RoundedRectangleView.swift
> +    @State var label: String
I created a `ButtonStyle` and that hasn't label.

2023-05-31 08:02 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickFieldView.swift
> +    // MARK: - Private interface
I will consider it and fix in this PR.

2023-05-31 08:39 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
We've discussed it one more time )

2023-05-31 08:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldViewAlignment.swift
> +    /// The corresponding value of the `HorizontalAlignment`.
Fixed

2023-05-31 08:42 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +            TextField(placeholder, text: $input)
We've discussed it on the call.

2023-05-31 08:43 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .multilineTextAlignment(alignment.textAlignment)
We've discussed it on the call and decided that it should be `multilineTextAlignment` and one line.

2023-05-31 08:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +struct DataInputFieldView: View {
Fixed

2023-05-31 08:48 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +    let alignment: DataInputFieldViewAlignment
To be able to set the alignment of the `LabelWithTextFieldView`.

2023-05-31 08:56 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +        DataInputFieldView(input: .constant(""),
Fixed

2023-05-31 08:56 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +                .lineLimit(dataInputFieldLineLimit)
Fixed

2023-05-31 08:59 UTC, kirpichonok commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S294JL6K3Q;
Sorry. I run the app on the phone and forgot to set the previous value.
Fixed

2023-05-31 10:42 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/DatePickerView.swift
> +/// A view with the label `Date` that allows selecting a calendar date by tapping on the field below the label.
Fixed

2023-05-31 11:43 UTC, YuliaNastiushkina reviewed
Please, resolve branch conflict.

2023-05-31 12:29 UTC, YuliaNastiushkina requested changes
Please, check structure of project.
You have 2 folders `View`.

Also, one more changes, check it please.

2023-05-31 12:29 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +    }
I cannot see how render second `TextField`.

```suggestion
    static var previews: some View {
    VStack {
        LabelWithTextFieldView(
            input: .constant(""),
            label: "Label",
            placeholder: "Placeholder",
            keyboardType: .default,
            alignment: .leading
        )
        LabelWithTextFieldView(
            input: .constant("Here's a field with a quite long fancy text that doesn't fit on one line."),
            label: "Here's a label with a quite long fancy text that doesn't fit on one line.",
            placeholder: "Placeholder",
            keyboardType: .default,
            alignment: .leading
        )
        }
    }
```

2023-05-31 13:20 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +    }
Fixed

2023-05-31 14:08 UTC, YuliaNastiushkina requested changes
I have one minor improvement.

2023-05-31 18:32 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +        }
Fixed

2023-06-01 05:33 UTC, levvaa approved these changes
LGTM

2023-06-01 06:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +    /// The selected date that is shown in the view.
nit:

```suggestion
    /// The date value being displayed and selected.
```

2023-06-01 06:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +        LabelWithDatePickerView(date: .constant(Date()),
nit:

```suggestion
        LabelWithDatePickerView(date: .constant(.now),
```

2023-06-01 06:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +                                labelText: "Date")
nit:

I'd suggest the following formatting to improve readability:

```suggestion
        LabelWithDatePickerView(
            date: .constant(Date()),
            labelText: "Date"
        )
```

2023-06-01 06:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/DataInputFieldView.swift
> +    let alignment: DataInputFieldViewAlignment
Can we just have 2 parameters, say:

```suggestion
let labelAlignment: HorizontalAlignment

let textFieldAlignment: TextAlignment
```

to avoid the `LabelWithTextFieldViewAlignment` type?
It seems excessive.

2023-06-01 06:44 UTC, dersim-davaod requested changes
Consider improvements and please avoid excessive types (try to use the existing).

2023-06-01 06:44 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +    let label: String
This is not a label, but text:

```suggestion
    /// A text displayed in the label.
    let labelText: String
```

2023-06-01 06:44 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +    let label: String
Please review the rest of code.

2023-06-01 06:46 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +			children = (
Seems we can put these files into the `Subviews` folder.

2023-06-01 07:04 UTC, YuliaNastiushkina approved these changes
LGTM.

2023-06-01 07:16 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +    /// The selected date that is shown in the view.
Fixed

2023-06-01 07:16 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +        LabelWithDatePickerView(date: .constant(Date()),
Fixed

2023-06-01 07:17 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithDatePickerView.swift
> +                                labelText: "Date")
Fixed

2023-06-01 08:10 UTC, kirpichonok commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +			children = (
Fixed

2023-06-01 08:11 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/LabelWithTextFieldView.swift
> +    let label: String
Fixed

2023-06-01 08:21 UTC, dersim-davaod requested changes
Please address all the open conversations.
Please resolve the conflicts.

2023-06-01 09:06 UTC, YuliaNastiushkina approved these changes

2023-06-01 09:20 UTC, levvaa approved these changes
LGTM

2023-06-01 09:25 UTC, dersim-davaod reviewed
Almost fine, but had a couple of questions:

2023-06-01 09:25 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    /// The text entered into the field.
nit:
```suggestion
    /// The text entered into the text field.
```

2023-06-01 09:25 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    let placeholder: String
This is not a placeholder, this is a text for placeholder, so you have to name it:
```suggestion
    let placeholderText: String
```

You haven't follow [my advice](https://github.com/ios-course/link-team-project/pull/51#discussion_r1212662943) and haven't double-check the PR, so as we have discussed I'm not going to review your later PRs anymore (in the current sprint).

2023-06-01 09:25 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    init(
Could you please explain why do you need this initiazer?

2023-06-01 09:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    /// The text entered into the field.
Fixed

2023-06-01 09:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    let placeholder: String
Fixed

2023-06-01 09:48 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/AddBillView/Subviews/LabelWithTextFieldView.swift
> +    init(
Not to pass alignments every time. The most times it's `leading`.

2023-06-01 10:42 UTC, dersim-davaod approved these changes
LGTM!

2023-06-01 10:47 UTC, merged