Creates navigation bar for history operations
ios-course/link-team-project pull request #52
Opened 2023-05-24 11:54 UTC by YuliaNastiushkina

# What 

Added navigation bar for History of operations of issue #44. 

# Why 

This PR closes #44. 

# How
Added navigation bar with title and button `Add`. The button does nothing.

#Important (need to discuss)
Title font size doesn't match with [App style guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines). Suggest using the current implementation.

2023-05-24 14:01 UTC, kirpichonok commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
Why the file in the root of the project?

2023-05-24 14:10 UTC, kirpichonok commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +                    .font(.system(size: fontBodySize, design: .default))
```suggestion
                    .font(.system(size: fontBodySize)
```
nit: 
Can we write in such a way?

2023-05-24 14:54 UTC, kirpichonok commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +// MARK: Internal Interface
I don't understand what do you want to mark with it?

2023-05-24 14:57 UTC, kirpichonok requested changes
Sorry, I don't understand how do we intent to use this type in our code?

2023-05-24 15:37 UTC, YuliaNastiushkina commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +// MARK: Internal Interface
That code below doesn't private.

2023-05-24 16:45 UTC, kirpichonok commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +// MARK: Internal Interface
I think it's redundant. It's not interface of the `NavigationBarForHistoryOfOperationView`.

2023-05-25 07:51 UTC, YuliaNastiushkina commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +// MARK: Internal Interface
Ok.

2023-05-25 08:44 UTC, YuliaNastiushkina commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
Will added in the folder View, after [issue#54](https://github.com/ios-course/link-team-project/issues/54) will be done.

2023-05-25 13:02 UTC, YuliaNastiushkina commented on JourneysSquad/NavigationBarForHistoryOfOperationView.swift
> +                    Text(toolBarItemTitle)
Fixed.

2023-05-25 13:39 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +struct HistoryOfOperationView: View {
I think it's should be Navigation Bar View
```suggestion
struct NavigationBarView: View {
```

2023-05-25 13:42 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +        NavigationStack {
Why we need `NavigationStack` here?

2023-05-26 11:31 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ContentView.swift
My fault, I will fix it.

2023-05-26 11:31 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +        NavigationStack {
Do you know how to create a navigation bar in a different way?
We need a navigation stack to add a list and be able to navigate between the current screen and the next, for example.
Please read about NavigationStack and recall what it is.

2023-05-26 11:31 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +            Text("Any other view can be placed here")
We will replace that text on List of bill rows, but now it just dummy text.
Try to create NavigationStack without any view and you will take an answer on your question :)

2023-05-26 11:31 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +struct HistoryOfOperationView: View {
No, this would be screen History of operation and we create navigation bar on this screen.
You can write or call me and I explain if you don't understand.

2023-05-26 12:01 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +        }
nit:

I'd suggest to make it this way.
It will allow more clear refactoring (in the following PR you will just replace everything inside the `VStack` with the new View(s).

Does that make sense?
```suggestion
        NavigationStack {
            VStack {
                Text("Any other view can be placed here")
            }
            .navigationTitle("History of Operations")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                Button("Add") {}
                    .font(.system(size: fontBodySize))
                    .fontWeight(.bold)
                    .foregroundColor(.blue)
            }
        }
```

2023-05-26 12:02 UTC, dersim-davaod approved these changes
LGTM, except one nit.

2023-05-26 12:06 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +        }
Yes, thanks!
Fixed.

2023-05-26 12:15 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +                Text("Any other view can be placed here")
```suggestion
                Text("")
```
nit

2023-05-26 12:17 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +            .navigationTitle("History of Operations")
Magic string

2023-05-26 12:19 UTC, kirpichonok requested changes
Correct one remark, please.

2023-05-26 12:37 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/HistoryOfOperationView.swift
> +            .navigationTitle("History of Operations")
Fixed.

2023-05-26 15:23 UTC, dersim-davaod approved these changes
LGTM

2023-05-29 05:07 UTC, kirpichonok approved these changes
LGTM

2023-05-29 05:07 UTC, kirpichonok approved these changes
LGTM

2023-05-29 08:08 UTC, levvaa approved these changes

2023-05-29 08:10 UTC, merged