Levitski/43 bill list view
ios-course/link-team-project pull request #58
Opened 2023-05-26 09:46 UTC by levvaa

What

Added list of bills  https://github.com/ios-course/link-team-project/issues/43.

Why

This PR closes https://github.com/ios-course/link-team-project/issues/43.

How

Created file BillListView;
Created file BillListViewModel;
Created file BillListDummyDate;

2023-05-26 13:14 UTC, dersim-davaod requested changes
Not bad!
Consider improvements, please:

2023-05-26 13:14 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
I can't read the code. Can you?

Please format it properly to improve readability (avoid too many operations on the the same line).

2023-05-26 13:14 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
Why you're using the deprecated initializer here?

2023-05-26 13:14 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +    static let listData: [BillListViewModel] = [
Why the model has the reference to the viewmodel?
This is the violation of unidirectional data flow in the MVVM.

2023-05-26 13:14 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +                    description: "Description1",
nit:

Please give the fields a bit more "real" names/descriptions/participants, so the app looks fancy even with the dummy data.

2023-05-26 13:14 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +/// A view displaying the list of bills.
There should be a blank line:
```suggestion
import SwiftUI

/// A view displaying the list of bills.
```

Please run linters before requesting the review.

2023-05-26 13:38 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +/// The instance of dummy list of bills to use in preview of views.
/// A dummy list of bills grouped into sections by date.

2023-05-26 13:39 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +/// The instance of dummy list of bills to use in preview of views.
```suggestion
/// A dummy list of bills grouped into sections by date.
```

2023-05-26 13:43 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +    /// List with data that will be displayed in the preview.
```suggestion
/// A dummy list of bills grouped into sections by date.
```

2023-05-26 13:45 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +/// The instance of dummy list of bills to use in preview of views.
```suggestion
/// Provides dummy data for the BillList view.
```

2023-05-26 13:50 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
The name of the file doesn't match with the name of the type.

2023-05-26 14:03 UTC, YuliaNastiushkina requested changes
Good job, thanks!
I have some improvements, please check.

2023-05-26 14:03 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
Does that changes should be in current PR ?

2023-05-26 14:03 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
Maybe it would be more readable ?

```suggestion
                Section(header: Text(section.headerText)
                .font(.system(size: fontBodySize))) {
```

2023-05-29 10:22 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/BillListViewModel.swift
> +    var id: String { headerText }
Our list is hardcoded so the header will be always unique. We will work on the view model in the future.

2023-05-29 10:22 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/BillListViewModel.swift
> +    /// The unique identifier of the bill list view model.
Fixed

2023-05-29 10:24 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
Fixed

2023-05-29 11:32 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
Fixed

2023-05-29 11:32 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +    static let listData: [BillListViewModel] = [
Fixed

2023-05-29 11:33 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +                    description: "Description1",
Fixed

2023-05-29 11:33 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +/// A view displaying the list of bills.
Fixed

2023-05-29 11:33 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
> +    /// List with data that will be displayed in the preview.
Fixed

2023-05-29 11:34 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Model/BillListDummyData.swift
Fixed

2023-05-29 11:38 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillRowView.swift
Yes, we need to show several rows in a section and to pass data for these rows.

2023-05-29 11:38 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/BillListViewModel.swift
> +    /// An array of `DummyBillRowViewModel` objects representing the rows of the bill list.
Fixed

2023-05-29 11:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/BillRowViewModel.swift
It does more convenient to hard-code data to output in the view.

2023-05-29 11:44 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +                Section(header: Text(section.headerText).font(.system(size: fontBodySize))) {
Fixed

2023-05-29 12:27 UTC, YuliaNastiushkina requested changes
Really good work!
I have some minor improvements.

2023-05-29 12:27 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillListViewModel.swift
> +/// Dummy view model that provides data to display for the `BillListView`.
```suggestion
/// Dummy view model that provides data to display for the list of bills.
```

2023-05-29 12:27 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    ///
```suggestion
```

2023-05-29 12:27 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummySectionViewModel.swift
> +    ///
```suggestion
```

2023-05-29 12:27 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/ViewModel/DummySectionViewModel.swift
> +    ///   - rows: A list of hardcoded bills those are grouped into the current section.
nit:
Why do you like word "hardcoded" ? :)
You can use "fixed" for example:
```suggestion
    ///   - rows: A list of fixed bills those are grouped into the current section.
```

2023-05-30 11:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/ViewModel/DummySectionViewModel.swift
> +    ///   - rows: A list of hardcoded bills those are grouped into the current section.
There's even better word "static": 
```suggestion
    ///   - rows: A static list of bills to show in the section.
```

2023-05-31 04:51 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillListView.swift
> +/// Displays a list of bills grouped into sections by date.
fixed

2023-05-31 04:51 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
fixed

2023-05-31 05:01 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
This name is used in another part of the code, and helps to understand what kind of view model it is.

2023-05-31 05:03 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummySectionViewModel.swift
> +    ///   - rows: A list of hardcoded bills those are grouped into the current section.
fixed. Used variant with `static list`

2023-05-31 05:06 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillListViewModel.swift
> +/// Dummy view model that provides data to display for the `BillListView`.
fixed

2023-05-31 05:08 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    ///
fixed

2023-05-31 05:08 UTC, levvaa commented on JourneysSquad/JourneysSquad/ViewModel/DummySectionViewModel.swift
> +    ///
fixed

2023-05-31 07:46 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/ViewModel/DummyBillRowViewModel.swift
> +    /// - Parameters:
```suggestion
    /// Initializes a new instance with the provided data.
    ///
    /// - Parameters:
```

2023-05-31 07:48 UTC, kirpichonok approved these changes
LGTM

2023-05-31 08:37 UTC, YuliaNastiushkina approved these changes
LGTM

2023-05-31 08:46 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
@levvaa  Could you please show me an example of code where the clarity will be lost if we make a rename?

2023-05-31 08:58 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
In the `BillListView` we use sectionViewModel. 
I think if i will rename this const, in the highlighted line it is not immediately clear what kind of view model is used.

<img width="486" alt="Screenshot 2023-05-31 at 16 50 03" src="https://github.com/ios-course/link-team-project/assets/120186417/56a27df0-778d-4a4f-81a8-c2e33474be06">

2023-05-31 10:03 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
```swift
BillSectionView(viewModel: sectionViewModel)
```
?

2023-05-31 10:50 UTC, levvaa commented on JourneysSquad/JourneysSquad/View/BillSectionView.swift
> +    let sectionViewModel: DummySectionViewModel
I have revised my opinion and agree with you.
fixed

2023-05-31 11:28 UTC, dersim-davaod approved these changes
LGTM

2023-05-31 11:35 UTC, merged