Add AppIconName, BlackCircleWithPlusButton, BlackRoundedRectangleButton
ios-course/link-team-project pull request #60
Opened 2023-05-28 17:32 UTC by kirpichonok

BlackCircleWithPlusButton, BlackRoundedRectangleButton
# What 

Added two `ButtonStyles` to create plus button(1 in the scheme) and `Save` button(2 in the scheme).

# Why 

This PR is part of  #4. 

## How

Added next UI elements:
- `BlackRoundedRectangleButton` and `BlackCircleWithPlusButton` button styles those help to create the button `Save` and `+`.

- extension `AppIconName` for String. It is a set of names for using UI elements such as buttons and `systemImage`.

# Scheme
<img width="532" alt="Screenshot 2023-05-28 at 20 27 50" src="https://github.com/ios-course/link-team-project/assets/110284165/63917818-c7e0-43e2-8147-a121e0a7fc61">
 Bill` according to AC of issue #4.

2023-05-29 05:54 UTC, YuliaNastiushkina requested changes

2023-05-29 05:54 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackCircleWithPlusButton.swift
> +    private let frameWidthAndHeight: CGFloat = 20
The name of constant confused. It is not entirely clear what this means, their amount or something else.
Maybe it would be better to split it and create 2 constants instead ?

2023-05-29 06:06 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackCircleWithPlusButton.swift
> +    private let frameWidthAndHeight: CGFloat = 20
Fixed

2023-05-29 07:06 UTC, YuliaNastiushkina approved these changes
Good job, thanks!

2023-05-29 09:07 UTC, dersim-davaod requested changes
Consider improvements please:

2023-05-29 09:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +        Image(systemName: String.AppIconName.plus)
nit:

Please use the type inferring:

```suggestion
        Image(systemName: .AppIconName.plus)
```

2023-05-29 09:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
Am I right that the frame is fixed for all `CircleWithPlusButton`s? What if the some view want the very big button with the `CircleWithPlusButton` style ?

2023-05-29 09:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Helpers/App Style/String+AppIconName.swift
> +    enum AppIconName {
Missed tests for the enum.

2023-05-29 09:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S294JL6K3Q;
Why you have put some development team here?

2023-05-29 09:07 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackRoundedRectangleButton.swift
> +        configuration.label
Could you please explain what this line does? Why do you need it here?

2023-05-29 12:12 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/App Style/String+AppIconName.swift
> +    /// The set of names for using UI elements.
Fixed

2023-05-29 12:13 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/App Style/String+AppIconName.swift
> +        /// The name used to create an image as a circle with a plus sign in the center.
Fixed

2023-05-29 12:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/App Style/String+AppIconName.swift
> +        /// The text for `Save` button label.
I've created a separate file `AppButtonLabelName`.

2023-05-29 12:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackRoundedRectangleButton.swift
> +            .buttonStyle(BlackRoundedRectangleButton())
Fixed

2023-05-29 12:32 UTC, kirpichonok commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = S294JL6K3Q;
Fixed

2023-05-30 10:55 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackRoundedRectangleButton.swift
> +/// Create a button as a black rectangle with rounded corners and white text inside.
Fixed

2023-05-30 11:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/App Style/String+AppIconName.swift
> +    enum AppIconName {
Fixed

2023-05-30 11:26 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
Fixed

2023-05-30 11:55 UTC, dersim-davaod requested changes
Consider minor improvements:

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Helpers/AppStyle/String+AppIconName.swift
> +        /// The name of the icon to show "A circle with a plus sign in the center".
Please make the name consistent with existing pattern:

// The name of the app icon representing a circle with a plus sign in the center.

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Helpers/String+AppButtonLabelName.swift
> +    enum AppButtonLabelName {
General question: are we going to re-use these names?
Why this is an internal-scoped enum?

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/Helpers/String+AppButtonLabelName.swift
> +    enum AppButtonLabelName {
nit:
```suggestion
    enum AppButtonLabelText {
```

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/AppIconNameTests.swift
> +final class AppIconNameTests: XCTestCase {
The name should be
```suggestion
final class StringAppIconNameTests: XCTestCase {
```

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/AppIconNameTests.swift
> +final class AppIconNameTests: XCTestCase {
Please review the rest of code.

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/String+AppButtonLabelNameTests.swift
> +}
```suggestion
    func testAppButtonLabelNamesHaveExpectedValues() {
        XCTAssertEqual(String.AppButtonLabelName.save, ""Save"")
        // Add more values here later if needed...
    }
}
```

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/String+AppButtonLabelNameTests.swift
> +}
Please review the rest of code.

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackRoundedRectangleButton.swift
> +        configuration.label
Could you please explain what was fixed? Looks like nothing was changed.

2023-05-30 11:55 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
Could you please explain what was fixed? Looks like nothing was changed.

2023-05-30 12:36 UTC, YuliaNastiushkina reviewed
Please, check structure of project.
It seems that after you merge main in your branch something went wrong.
For example, you have 2 folders `Helpers`.

Resolve conflict, please.

2023-05-31 05:23 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/AppStyle/String+AppIconName.swift
> +        /// The name of the icon to show "A circle with a plus sign in the center".
Fixed

2023-05-31 05:28 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/String+AppButtonLabelName.swift
> +    enum AppButtonLabelName {
Yes. We can use it for all `Save` buttons in the project.

2023-05-31 05:30 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/String+AppButtonLabelName.swift
> +    enum AppButtonLabelName {
Fixed

2023-05-31 05:59 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/AppIconNameTests.swift
> +final class AppIconNameTests: XCTestCase {
Fixed

2023-05-31 06:00 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Helpers/String+AppButtonLabelNameTests.swift
> +}
Fixed

2023-05-31 06:41 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/BlackRoundedRectangleButton.swift
> +        configuration.label
@dersim-davaod 
The documentation is pure. I can't adjust button label without this "type-erased label" because I don't provide another view, if I've understood correctly.

2023-05-31 07:42 UTC, levvaa requested changes

2023-05-31 07:42 UTC, levvaa commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/String+AppIconNameTests.swift
> +        // add new checks later...
Why do we leave this comment here without marking it TODO if something will be added?

2023-05-31 07:46 UTC, levvaa commented
I see that some comments from other reviewers have gone unanswered 🙂

2023-05-31 08:46 UTC, YuliaNastiushkina approved these changes
LGTM, except for the comments of other reviewers.

2023-05-31 11:40 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
I've added initialiser with passed `width` and `height`.

2023-05-31 11:46 UTC, YuliaNastiushkina reviewed
Please, resolve branch conflict.

2023-05-31 11:47 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
No, the style must not prevent you to use the `.frame` modifier in the client's code.

2023-05-31 11:47 UTC, dersim-davaod requested changes
Please resolve conflicts.
PTAL at the unresolved conversations.

2023-05-31 11:48 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/String+AppIconNameTests.swift
> +        // add new checks later...
Fixed

2023-05-31 11:55 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +            .frame(width: frameWidth,
Fixed

2023-05-31 12:13 UTC, dersim-davaod requested changes
Consider minor improvements:

2023-05-31 12:13 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +        Button("") {}
Preview doesn't show the second button.
Please double check the preview / run the app before re-requesting review.

2023-05-31 12:13 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/String+AppButtonLabelNameTests.swift
> +        // add new checks later...
I still see the useless comments.
Please fix the issues we have discussed earlier.
Please double-check the changes before re-requesting review.

2023-05-31 12:27 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/View/ReusableStyles/CircleWithPlusButton.swift
> +        Button("") {}
Sorry, you're right. Fixed

2023-05-31 12:29 UTC, kirpichonok commented on JourneysSquad/JourneysSquadTests/Helpers/String+AppButtonLabelNameTests.swift
> +        // add new checks later...
Sorry, I work on it. 
Fixed.

2023-05-31 12:32 UTC, dersim-davaod approved these changes
LGTM

2023-05-31 14:03 UTC, merged