Creates navigation bar for struct `AddBillView`
ios-course/link-team-project pull request #61
Opened 2023-05-29 11:22 UTC by YuliaNastiushkina

# What 

Added navigation bar for struct `AddBillView` with title and `Back` button.

# Why 

This PR closed  #57. 

## How

Created struct `AddBillView`.
Added navigation bar with:
* title "Add new bill"
* button `Back` that do nothing yet.

2023-05-29 14:41 UTC, dersim-davaod requested changes
Looks good!
Please consider minor improvements:

2023-05-29 14:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +/// Contain navigation bar with title and button `Back` now.
nit:

Be consistent and use Present Simple tense:
```suggestion
/// Contains navigation bar with title and button `Back` now.
```

2023-05-29 14:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +/// Contain navigation bar with title and button `Back` now.
nit:

```suggestion
/// A view with that allows to create a new bill to split.
/// The user can navigate back from the view.
```

2023-05-29 14:41 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +                           .foregroundColor(.black)
nit: Do we need this modifier?

2023-05-29 16:23 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +                               Image(systemName: "chevron.backward")
Thanks, fixed it.

2023-05-29 16:23 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +/// Contain navigation bar with title and button `Back` now.
Fixed.

2023-05-29 16:23 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +/// Contain navigation bar with title and button `Back` now.
Fixed.

2023-05-29 16:23 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +    private let titleText = "Add new bill"
Fixed.

2023-05-29 16:23 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +                           .foregroundColor(.black)
Thanks, fixed.

2023-05-29 16:24 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/View/AddBillView.swift
> +                           .foregroundColor(.black)
Yes, because we need button with black color.

2023-05-30 05:35 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/AppStyle/StringExtensionAppIconName.swift
I see you add the same file as in my PR. Can you rename this file according to my version ["String+AppIconName"](https://github.com/ios-course/link-team-project/pull/60/files#diff-2a23c8a7fd360b1ff6c5a6272c613a066a69b115db966d5855a02ab1c127b983)?

2023-05-30 05:37 UTC, kirpichonok requested changes
Resolve one question, please.

2023-05-30 05:40 UTC, kirpichonok commented on JourneysSquad/JourneysSquad/Helpers/AppStyle/StringExtensionAppIconName.swift
It regards to test target file too.

2023-05-30 06:19 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquad/Helpers/AppStyle/StringExtensionAppIconName.swift
Fixed.

2023-05-30 06:49 UTC, dersim-davaod approved these changes
LGTM

2023-05-30 06:49 UTC, dersim-davaod commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/String+AppIconNameTests.swift
> +    }
nit:

```suggestion
    func testAppIconNamesHaveExpectedValues() {
        XCTAssertEqual(String.AppIconName.backwardChevron, "chevron.backward")
        // add new checks later...
    }
```

2023-05-30 07:05 UTC, YuliaNastiushkina commented on JourneysSquad/JourneysSquadTests/Helpers/AppStyle/String+AppIconNameTests.swift
> +    }
Thanks, fixed it.

2023-05-30 10:37 UTC, kirpichonok approved these changes
LGTM

2023-05-30 10:45 UTC, dersim-davaod approved these changes
LGTM

2023-05-30 10:45 UTC, merged