Combined navigation bar and list of bills
ios-course/link-team-project pull request #66
Opened 2023-05-31 14:50 UTC by levvaa

### What?

Combined navigation bar with static list of bills. 

### Why?

Closes #47 

### How?

`BillListView` added into the `HistoryOfOperationsView`

2023-05-31 14:56 UTC, dersim-davaod requested changes
Please make the proper project structure.

As an example I'd suggest to put the `HistoryOfOperationView` into a separate group. Then please put view's components (`BillListView`, `BillRowView`, etc) into the `HistoryOfOperationView/Subviews` dir or something like that to show the hierarchy of views.

2023-06-01 05:51 UTC, kirpichonok approved these changes
LGTM

2023-06-01 06:21 UTC, dersim-davaod approved these changes
LGTM, but consider minor improvements please:

2023-06-01 06:21 UTC, dersim-davaod commented on CHANGELOG.md
> +- `HistoryOfOperationsView` contains a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
nit:

This is not an addition, but the update.

2023-06-01 06:21 UTC, dersim-davaod commented on CHANGELOG.md
> +- `HistoryOfOperationsView` contains a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
```suggestion
- `HistoryOfOperationsView` containing a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
```

2023-06-01 06:21 UTC, dersim-davaod commented on CHANGELOG.md
> +- `HistoryOfOperationsView` contains a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
nit:

I'd suggest to make it more clear.

```suggestion
- `HistoryOfOperationsView` screen where user can see the static list of operations/bills and navigate to the `AddBill` screen [#47](https://github.com/ios-course/link-team-project/issues/47)
```

2023-06-01 06:21 UTC, dersim-davaod commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				ABDE72172A279FAA003810A8 /* HistoryOfOperationsSubviews */,
nit:

`Subviews` would be enough, but that's fine.

```suggestion
				ABDE72172A279FAA003810A8 /* Subviews */,
```

2023-06-01 06:52 UTC, levvaa commented on JourneysSquad/JourneysSquad.xcodeproj/project.pbxproj
> +				ABDE72172A279FAA003810A8 /* HistoryOfOperationsSubviews */,
Yeah! You right. Fixed.

2023-06-01 07:00 UTC, levvaa commented on CHANGELOG.md
> +- `HistoryOfOperationsView` contains a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
Your version looks better. I used it!

2023-06-01 07:09 UTC, levvaa commented on CHANGELOG.md
> +- `HistoryOfOperationsView` contains a navigation bar and a list with static data [#47](https://github.com/ios-course/link-team-project/issues/47)
fixed. Used your suggestion below

2023-06-01 07:15 UTC, merged